{% set name = "dimcli" %}
{% set version = "0.9.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dimcli-{{ version }}.tar.gz
  sha256: c72b5add3c0e2c9a62b106a745fb36d8f21c38f02ede2456b516595d2a33e0ac

build:
  number: 0
  noarch: python
  entry_points:
    - dimcli = dimcli.main_cli:main_cli
    - dimcli_quicktest = dimcli.tests.quicktest:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - click
    - ipython
    - packaging
    - pandas
    - prompt-toolkit
    - pygments
    - recommonmark
    - requests
    - tqdm

test:
  imports:
    - dimcli
  commands:
    - pip check
    - dimcli --help
  requires:
    - pip

about:
  home: https://github.com/digital-science/dimcli
  summary: Python REPL/API for accessing dimensions.ai.
  license: MIT
  license_file: LICENSE
  description: |
    Dimcli is a Python client for accessing the Dimensions Analytics API. 
    It makes it easier to authenticate against the API, send queries to it 
    and process the JSON data being returned.
  doc_url: https://digital-science.github.io/dimcli/
  dev_url: https://github.com/digital-science/dimcli

extra:
  recipe-maintainers:
    - sugatoray
